version: '3'
services:
    db:
        image: postgres:11-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=postgres            
        volumes:
            - $DB_LOCAL_PATH:$DB_CONTAINER_PATH
    odoo:
        image: odoo:13.0
        depends_on:
            - db-develop
        ports:
            - "8047:8069"
        volumes:
            - $CONF_LOCAL_PATH:$CONF_CONTAINER_PATH
        command: odoo -i base
        environment:
            - DB_PORT_5432_TCP_ADDR=db-develop
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=$DB_USER
            - DB_ENV_POSTGRES_PASSWORD=$DB_PASSWORD
            - DB_ENV_POSTGRES_DB=postgres
            - ADMIN_PASS=$ODOO_ADMIN_PASS
